name: MoonBit Check, Build and Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    name: Check & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5

      - name: setup-node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: install-ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: install-macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: install-windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://cli.moonbitlang.com/install/powershell.ps1'))
          echo "$env:USERPROFILE\.moon\bin" >> $env:GITHUB_PATH

      - name: verify-installation
        run: |
          moon version --all
          moon update

      - name: check-all-targets
        run: |
          moon check --target all --deny-warn

      - name: build-native
        run: |
          moon build --target native --deny-warn

      - name: check-formatting
        run: |
          moon fmt
          git diff --exit-code

      - name: generate-and-check-info
        run: |
          moon info
          git diff --exit-code

      - name: run-all-tests
        run: |
          moon test --target all --deny-warn
